# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    user_login_route_listener:
        class: AppBundle\Event\UserLoginRouteListener
        arguments:
            - @security.token_storage
            - @router
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    registration_route_listener:
        class: AppBundle\Event\RegistrationRouteListener
        arguments:
            - @router
            - "%registration_enabled%"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }



    content_voter:
        class: AppBundle\Security\Authorization\Voter\ContentVoter
        public: false
        tags:
            - { name: security.voter }

    super_content_voter:
        class: AppBundle\Security\Authorization\Voter\SuperContentVoter
        public: false
        tags:
            - { name: security.voter }

    always_true_voter:
        class: AppBundle\Security\Authorization\Voter\AlwaysTrueVoter
        public: false
        tags:
            - { name: security.voter }